apiVersion: v1
kind: Pod
metadata:
  name: app-livenessProbe
  namespace: demo
spec:
  containers:
   - image: gcr.io/k8s-k3s/demo:v1.0.0
     name: app
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10

    ports:
        - containerPort: 8080
          name: http