apiVersion: v1
kind: Pod
metadata:
  name: app-livenessProbe
  namespace: demo
spec:
  containers:
  - name: app-livenessProbe
    image: gcr.io/k8s-k3s/demo:v1.0.0
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10